package RefractoredVersion.TestScript.Config;

public enum ShieldType {
    ALL_SLOWER,
    EXPLORE_FUTURE_ACTION,
    EXPLORE_FUTURE_BETTER_REFERENCE_ACTION,
    EXPLORE_FUTURE_RSS_ACTION,
    EXPLORE_FUTURE_RSS_O_ACTION,
    STARK_NATIVE,
    STARK_NATIVE_RANDOM_IDM,
    HEURISTIC,
    TTC_STOCHASTIC_HEURISTIC,
    RECO_4HZ,
    HEURISTIC_4HZ,
    INSTANT_HEURISTIC,
    EXPLORE_FUTURE_SMARTER_ACTION,
    EXPLORE_FUTURE_DELAYED_ACTION
}
