package RefractoredVersion.TestScript.Config;

public enum ShieldType {
    NONE,
    EXPLORE_FUTURE_ACTION,
    EXPLORE_FUTURE_BETTER_REFERENCE_ACTION,
    STARK_NATIVE,
    STARK_NATIVE_RANDOM_IDM,
    HEURISTIC,
    TTC_STOCHASTIC_HEURISTIC,
    RECO_4HZ,
    HEURISTIC_4HZ,
    EXPLORE_FUTURE_DELAYED_ACTION,
    STARK_NATIVE_DELAYED_ACTION
}
