package RefractoredVersion.TestScript.Config;

public enum ShieldType {
    ALL_SLOWER,
    EXPLORE_FUTURE_ACTION,
    EXPLORE_FUTURE_BETTER_REFERENCE_ACTION,
    EXPLORE_FUTURE_RSS_ACTION,
    EXPLORE_FUTURE_RSS_O_ACTION,
    STARK_NATIVE,
    EXPLORE_FUTURE_SMARTER_ACTION,
    EXPLORE_FUTURE_DELAYED_ACTION
}
