package RefractoredVersion.Shield;

import RefractoredVersion.Engine.Action;
import RefractoredVersion.Engine.JavaHighwayEngine;
import RefractoredVersion.Engine.JavaHighwayEngineUtils;
import RefractoredVersion.Engine.vehicle.NonNpcVehicle;
import RefractoredVersion.Engine.vehicle.Vehicle;
import it.unicam.quasylab.jspear.ds.DataState;
import it.unicam.quasylab.jspear.ds.DataStateUpdate;
import org.apache.commons.math3.random.RandomGenerator;

import java.util.List;

/**
 * STARK-native counterpart of {@link ExploreFutureDelayedActionShield}.
 *
 * <p>The ego keeps an IDLE intention until {@code delayStep} prediction
 * transitions have elapsed. The candidate action is then applied, followed by
 * the recovery actions at one-second intervals. NPC behaviour and low-level
 * motion are generated by the inherited STARK controller and environment.</p>
 */
public class StarkNativeDelayedActionShield extends StarkNativeShield {
    private final int delayStep;

    public StarkNativeDelayedActionShield(JavaHighwayEngine sourceEngine,
                                          List<Action> futureActions,
                                          int delayStep) {
        super(sourceEngine, futureActions);
        if (delayStep < 1) {
            throw new IllegalArgumentException("delayStep must be at least 1.");
        }
        this.delayStep = delayStep;
    }

    @Override
    protected int lastNativePredictionStep(List<Action> actionSequence) {
        return Math.max(
                0,
                actionSequence.size() * sourceEngine.getFrequency() + delayStep - 1
        );
    }

    @Override
    protected List<DataStateUpdate> getControllerUpdates(RandomGenerator rg,
                                                         DataState state,
                                                         List<Action> actionSequence) {
        List<Vehicle> vehicles = vehiclesFromState(state);
        JavaHighwayEngine nativeEngine = nativeEngineFor(state, vehicles);
        Vehicle ego = egoVehicle(vehicles);

        if (ego != null) {
            if (state.getStep() % sourceEngine.getFrequency() == 0) {
                applyAction(ego, Action.IDLE);
            }

            int shiftedStep = state.getStep() - delayStep;
            if (shiftedStep >= 0 && shiftedStep % sourceEngine.getFrequency() == 0) {
                int actionIndex = shiftedStep / sourceEngine.getFrequency();
                if (actionIndex >= actionSequence.size()) {
                    throw new IllegalStateException(String.format(
                            "Missing delayed native shield action at index %d, actionSequence size is %d",
                            actionIndex,
                            actionSequence.size()
                    ));
                }
                applyAction(ego, actionSequence.get(actionIndex));
            }
        }

        try {
            for (Vehicle vehicle : vehicles) {
                if (!(vehicle instanceof NonNpcVehicle)) {
                    vehicle.setTargetLaneIndex(JavaHighwayEngineUtils.sandboxComputeTargetLane(
                            vehicle,
                            vehicles,
                            List.of(0, 1),
                            nativeEngine
                    ));
                }
                vehicle.plannedAcceleration =
                        JavaHighwayEngineUtils.computeIdmAcceleration(vehicle, vehicles);
            }
        } catch (Exception e) {
            throw new IllegalStateException("Failed to apply delayed STARK-native highway controller", e);
        }

        return updatesForVehicles(vehicles, state);
    }
}
